version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isi-burger-app
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: isi_burger
      DB_USERNAME: isi_user
      DB_PASSWORD: passer
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html    
    networks:
      - isi-burger-net

  db:
    image: mysql:8.0
    container_name: isi-burger-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: isi_burger
      MYSQL_USER: isi_user
      MYSQL_PASSWORD: passer
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - isi-burger-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: isi-burger-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8082:80"   # 🔥 CHANGÉ (évite conflit 8081)
    depends_on:
      - db
    networks:
      - isi-burger-net

volumes:
  db_data:

networks:
  isi-burger-net:
    driver: bridge